### ISSUE TITLE
Please provide environment variable "GIT_NAME" and "GIT_EMAIL".

### ISSUE THREAD

**Issue by sylvesterjakubowski** [axeclbr/docker-git#4]
```
[sly@box git]$ sudo docker run -e "GIT_NAME=SylvesterJakubowski" -e "GIT_EMAIL=sjakubowski@someemail.com" --entrypoint=/bin/cat axeclbr/git /root/git > $HOME/bin/dgit && chmod +x $HOME/bin/dgit
[sly@box git]$ dgit clone https://github.com/mozart-analytics/grails-docker.git
Please provide environment variable "GIT_NAME" and "GIT_EMAIL".
[sly@box git]$ dgit -e "GIT_NAME=SylvesterJakubowski" -e "GIT_EMAIL=sjakubowski@someemail.com" clone https://github.com/mozart-analytics/grails-docker.git
Please provide environment variable "GIT_NAME" and "GIT_EMAIL".
````

Looks like it requires the ENV vars but doesn't accept them in either the new `dgit` command or when setting up the bin.

Would have been a useful util, this repo is the most relevant hit on dockerhub.

Thanks.

**Comment by axeclbr** [comment]
Hi @sylvesterjakubowski,

the script does not read variables passed with `-e`. You should just set them in the environment with `export` or － much more convenient － in a configuration file of your shell.

If you have the correct setup a command like `dgit clone https://github.com/mozart-analytics/grails-docker.git` should just work. There is no need to explicitly write the variables again and again.

Please try it out and tell me if you still have problems.

**Comment by axeclbr** [comment]
Closed this issue, because no response from OP. Please reopen, if necessary.
